# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ML_nbdev_project',
                'doc_host': 'https://SamAdebisi.github.io',
                'git_url': 'https://github.com/SamAdebisi/ML_nbdev_project',
                'lib_path': 'ML_nbdev_project'},
  'syms': {'ML_nbdev_project.core': {'ML_nbdev_project.core.foo': ('core.html#foo', 'ML_nbdev_project/core.py')}}}
